export { default as WelcomePage } from "./WelcomePage"
export { default as TouristHomePage } from "./TouristHomePage"
export { default as TouristLoginPage } from "./TouristLoginPage"
export { default as TouristSignUpPage } from "./TouristSignUpPage"
export { default as TouristGuidePage } from "./TouristGuidePage"
export { default as GuideHomePage } from "./GuideHomePage"
export { default as GuideLoginPage } from "./GuideLoginPage"
export { default as IndividualGuidePage } from "./IndividualGuidePage"
