export const filters  = {
    'Historical': 'HISTORICAL',
    'Outdoor activities': 'OUTDOOR_ACTIVITIES',
    'Cultural': 'CULTURAL',
    'Dining': 'DINING',
    'Music': 'MUSIC',
    'Female only': 'FEMALE_FRIENDLY',
    'Disability friendly': 'DISABILITY_FRIENDLY',
    'Art': 'ART',
    'Sports': 'SPORTS',
    'Educational': 'EDUCATIONAL',
    'Entertainment': 'ENTERTAINMENT',
    'Nature': 'NATURE',
    'Shopping': 'SHOPPING',
    'Technology': 'TECHNOLOGY',
    'Science': 'SCIENCE',
    'Fitness': 'FITNESS',
    'Family friendly': 'FAMILY_FRIENDLY',
    'Adventure': 'ADVENTURE',
    'Workshops': 'WORKSHOPS',
    'Holiday events': 'HOLIDAY_EVENTS',
    'Literature': 'LITERATURE',
    'Gaming': 'GAMING',
    'Photography': 'PHOTOGRAPHY',
    'Wellness': 'WELLNESS',
    'Food': 'FOOD',
    'Nightlife': 'NIGHTLIFE',
};
